pack:
  id: bmad-product-manager
  name: BMAD Product Manager
  version: 1.0.0
  description: >-
    Comprehensive Product Management expansion pack for BMad Method - Full product 
    lifecycle management with JTBD, OKR, RICE frameworks. Supports B2B/B2C tech 
    products with Agile/Lean methodologies and cross-functional collaboration.
  author: BMAD Community
  tags:
    - product-management
    - jobs-to-be-done
    - okr-planning
    - rice-prioritization
    - agile
    - lean
    - product-strategy
  
  slashPrefix: bmadpm
  
  agents:
    - product-lead
    - product-analyst
    - product-strategist
    - technical-pm
  
  primaryUseCase: |
    Enable end-to-end product management from discovery to delivery, with frameworks 
    for prioritization, planning, and execution in tech product environments.
  
  capabilities:
    - jobs_to_be_done
    - okr_planning
    - rice_prioritization
    - platform_thinking
    - product_analytics
    - roadmap_planning
    - launch_management
  
  dependencies:
    required:
      - bmad-core
    recommended:
      - bmad-market-researcher
      - bmad-pmo-agile
      - bmad-strategy-consulting
  
  integration_points:
    - market_validation
    - agile_execution
    - strategic_alignment
    - customer_feedback
  
  metadata:
    min_bmad_version: "1.0.0"
    last_updated: "2024-01-31"
    stability: "stable"