name = "bmad-demo-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Account ID - replace with your own
# account_id = "your-account-id"

# KV Namespaces for storing pack data
kv_namespaces = [
  { binding = "PACKS_KV", id = "your-kv-namespace-id", preview_id = "your-preview-kv-id" }
]

# Durable Objects for WebSocket handling
[[durable_objects.bindings]]
name = "WEBSOCKET_SESSIONS"
class_name = "WebSocketSession"

[[migrations]]
tag = "v1"
new_classes = ["WebSocketSession"]

# Environment variables
[vars]
ENVIRONMENT = "production"

# Development settings
[env.development]
vars = { ENVIRONMENT = "development" }

# Routes
routes = [
  { pattern = "bmad-demo.workers.dev", custom_domain = true }
]