name: bmad-strategy-consulting
version: 1.0.0
short-title: Strategy Consulting Pack
description: >-
  Elite Strategy Consulting expansion pack for BMad Method - McKinsey, BCG, and 
  Bain-inspired strategic analysis, long-term planning, and organizational 
  alignment. Provides frameworks, tools, and methodologies used by top-tier 
  strategy consulting firms.
author: BMad Community
slashPrefix: bmadsc