version: '3.8'

services:
  # Local WebSocket server
  local-server:
    build:
      context: .
      dockerfile: docker/local-server/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - PACKS_DIR=/packs
    volumes:
      # Mount local expansion packs directory
      - ../BMAD-METHOD/expansion-packs:/packs:ro
      # Mount source for development
      - ./docker/local-server/src:/app/docker/local-server/src
      - ./packages:/app/packages
    command: pnpm dev

  # SvelteKit web app (optional - can run separately)
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_MODE=local
      - VITE_API_URL=http://localhost:3001/api
      - VITE_WS_URL=ws://localhost:3001/ws
    volumes:
      - ./apps/web:/app/apps/web
      - ./packages:/app/packages
    depends_on:
      - local-server
    command: pnpm dev:web

volumes:
  pnpm-store: